timezone:    Europe/Berlin
future:      false
# The allowed values are 'rouge', 'pygments' or null.
highlighter: rouge
# markdown - Valid options are [ maruku | rdiscount | kramdown | redcarpet ]
markdown: kramdown
lsi:         false
# permalink:   "/:title"
url: "https://aaellen.github.io/" 
#baseurl: """

-kramdown:
  ## for german: "sbquo,lsquo,bdquo,ldquo"
  smart_quotes: lsquo,rsquo,ldquo,rdquo

name: AAellen # portfolio
title: AAellen
author: AAellen
email: aaellen01@gmail.com
github_username:  AAellen
description: >- # this means to ignore newlines until theme
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

sass:
  style:     :compressed

defaults:
-
  scope:
    type: "pages"
  values:
    js_includes: []
    title_prefix: "AAellen - "



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
