timezone:    Europe/Berlin
future:      false
# Set baseurl to the base path of the site eg "/mytalk"
# baseurl:     "/github-slideshow"
# The allowed values are 'rouge', 'pygments' or null.
highlighter: rouge
# markdown - Valid options are [ maruku | rdiscount | kramdown | redcarpet ]
name: AAellen # portfolio
markdown: kramdown
lsi:         false
permalink:   "/:title"
url: "https://aaellen.github.io/" 

kramdown:
  ## for german: "sbquo,lsquo,bdquo,ldquo"
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jemoji

title: AAellen
author: AAellen
theme: jekyll-theme-cayman
#excerpt_separator: <!--more-->

sass:
  style:     :compressed

  defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      js_includes: []
      title_prefix: "AAellen - "
